### ISSUE TITLE
Support for Alfresco One 5.0.x

### ISSUE THREAD

**Issue by bengrah-miller** [Gagravarr/AlfrescoDataListDownload#2]
Hi - I know this is probably not the place to ask this but I couldn't find any other method of contact. Can you confirm if this extension would work against Alfresco One 5.0.2? On the Add-Ons page it says the extension only supports 4.0 still, is that still the case?

Thanks,
ben.

**Comment by Gagravarr** [comment]
I've updated the readme and the add-ons page - 5.0.2 is fully supported. I know, as that's what we use!

I've also pushed some binaries as a formal build, to hopefully make the installation process easier
